MY_ANS_Q4 = ""
OTHER_ANS_Q4 = ""

MY_ANS_Q5 = "Brad Pitt, Hugh Jackman, Scarlett Johansson, Amy Adams, Chloe Grace Moretz, Johnny Depp"
OTHER_ANS_Q5 = "Brad Pitt, Chloe Grace Moretz, Johnny Depp, Amy Adams, Hugh Jackman, Scarlett Johansson"

MY_ANS_Q6 = "Christian Bale, Anne Hathaway, Hugh Jackman, Scarlett Johansson, Matt Damon, Mark Wahlberg, Brad Pitt, Christopher Plummer, Tom Hanks, Bryce Dallas Howard, Chiwetel Ejiofor, Ben Kingsley, Gerard Butler, Eva Green, Judi Dench, Will Smith, Jennifer Connelly, Tom Cruise, Emily Blunt, Kevin Spacey, Samuel L. Jackson, Steve Carell, Edward Norton, Will Ferrell, Denzel Washington, Russell Crowe, Toni Collette, Meryl Streep, Morgan Freeman, Dominic West, Owen Wilson, Michelle Monaghan, Jessica Biel, Dustin Hoffman, Ben Whishaw, Paula Patton, Abbie Cornish, Johnny Depp, Jack Davenport, Rachel Weisz, Ellen Burstyn, Kang-ho Song, Jeremy Irons, Marion Cotillard, Kirsten Dunst, Jennifer Aniston, Justin Theroux, Maya Rudolph, Kate Bosworth, Audrey Tautou, Luke Wilson, Sacha Baron Cohen, Bob Balaban"
OTHER_ANS_Q6 = "Abbie Cornish, Anne Hathaway, Audrey Tautou, Ben Kingsley, Ben Whishaw, Bob Balaban, Brad Pitt, Bryce Dallas Howard, Chiwetel Ejiofor, Christian Bale, Christopher Plummer, Denzel Washington, Dominic West, Dustin Hoffman, Edward Norton, Ellen Burstyn, Emily Blunt, Eva Green, Gerard Butler, Hugh Jackman, Jack Davenport, Jennifer Aniston, Jennifer Connelly, Jeremy Irons, Jessica Biel, Johnny Depp, Judi Dench, Justin Theroux, Kang-ho Song, Kate Bosworth, Kevin Spacey, Kirsten Dunst, Luke Wilson, Marion Cotillard, Mark Wahlberg, Matt Damon, Maya Rudolph, Meryl Streep, Michelle Monaghan, Morgan Freeman, Owen Wilson, Paula Patton, Rachel Weisz, Russell Crowe, Sacha Baron Cohen, Samuel L. Jackson, Scarlett Johansson, Steve Carell, Tom Cruise, Tom Hanks, Toni Collette, Will Ferrell, Will Smith"

MY_ANS_Q7 = """
Penelope Cruz, Anne Hathaway, Rebecca Hall, Eva Green, Christian Bale, Mia Wasikowska, Benedict Cumberbatch, Michelle Pfeiffer, Adam Brody, Orlando Bloom, Keira Knightley, Timothy Spall, Jack Davenport, Ian McShane, Geoffrey Rush, Jason Clarke, Christian Stolte, Cillian Murphy, Lily-Rose Depp, Alan Rickman, Helena Bonham Carter, Joel Edgerton, Morgan Freeman, Tom Wilkinson, Dakota Johnson, Harley Quinn Smith, Armie Hammer, William Fichtner, Ben Stiller, Woody Allen, Jesse Eisenberg, Michael Fassbender, Ellen Page, Owen Wilson, Cameron Diaz, Javier Bardem, Will Ferrell, Jim Sturgess, Russell Crowe, Rene Russo, Matthew McConaughey, George Lopez, Adrian Grenier, Tom Mison, Oliver Platt, Emily Blunt, Jake Gyllenhaal, Amanda Seyfried, Jessica Chastain, Bryan Greenberg, Austin Stowell, Judy Greer, Jason Sudeikis, Gary Oldman, Tim Blake Nelson, Meryl Streep, Kate Hudson, Robert De Niro, Anders Holm, Karen Disher, Patricia Clarkson, Hugh Jackman, Mackenzie Foy, Tom Hardy, Candice Bergen, Scarlett Johansson, Jim Broadbent, Jeremy Renner, Allison Tolman, Jason Bateman, Eric Bana, Ciaran Hinds, Jon Hamm, Maria Dizzia, Michael C. Hall, Tracy Letts, Ben Affleck, Christopher Evan Welch, Samuel L. Jackson, Asa Butterfield, Judi Dench, Sullivan Stapleton, Daniel Craig, Hans Matheson, Lena Headey, Jeffrey Wright, Zoe Saldana, Zach Grenier, Oscar Isaac, Amy Adams, Heath Ledger, Michael Caine, Mark Wahlberg, Natalie Portman, Cate Blanchett, Anton Yelchin, Aaron Eckhart, Ben Kingsley, Sigourney Weaver, Woody Harrelson, Brian Dennehy, Moon Bloodgood, Jennifer Lawrence, Steve Carell, Sam Worthington, Charlotte Le Bon, Steve Zahn, Casey Affleck, Jeremy Davies, Ryan Gosling, Melissa Leo, Bradley Cooper, Daniel Gimenez Cacho, Brad Pitt, Jamie Bell, Charlie Hunnam, Su Elliot, Tom Hiddleston, Benedict Wong, Allen Leech, Zachary Quinto, Matthew Goode, Chiwetel Ejiofor, Rachel McAdams, Chris Pine, John D'Leo, Nikki Blonsky, Dianna Agron, Queen Latifah, John Travolta, Megan Fox, Johnny Simmons, Saoirse Ronan, Jude Law, Kenneth Branagh, Adam Levine, Hailee Steinfeld, Mark Ruffalo, Aaron Taylor-Johnson, Matthew Macfadyen, James McAvoy, Kevin Costner, Brenda Blethyn, Andrew Scott, Rachel Weisz, David Oyelowo, Tom Felton, Rosamund Pike, Angelina Jolie, Jason Statham, Tyrese Gibson, Jack Black, Joan Allen, Dwayne Johnson, Dustin Hoffman, Joseph Fiennes, John Hurt, Colin Firth, Derek Jacobi, Sylvia Hoeks, Sam Neill, Nicholas Hope, Donald Sutherland, Ewen Leslie, Liana Liberato, Clive Owen, Channing Tatum, Jai Courtney, Ang Phula Sherpa, Arnold Schwarzenegger, Jamie Foxx, Martin Henderson, Catherine Keener, Shia LaBeouf, Emilia Clarke, Maggie Gyllenhaal, Thomas M. Wright, Guy Pearce, Ben Whishaw, Jamie Dornan, Chris Evans, Olivia Wilde, Justin Timberlake, Brie Larson, Brian Caspe, Chris Hemsworth, Rose Byrne, Sharlto Copley, Karel Hermanek Jr., Brendan Gleeson, Michelle Yeoh, Aaron Paul, Francesc Albiol, Barkhad Abdi, Helen Mirren, Richard Madden, Lily James, Ruth Negga, Michael Shannon, Dean Mumford, Chris Pratt, Mark Strong, Kirsten Dunst, Nick Nolte, Adam Driver, Tobey Maguire, Jennifer Morrison, Will Dalton, Carey Mulligan, Leonardo DiCaprio, Gerard Butler, Bruce Willis, Andrea Riseborough, Tom Cruise, Olga Kurylenko, Michelle Monaghan, Min-sik Choi, Lucy Liu, Ed Harris, Josh Hartnett, Angela Bassett, Mary-Louise Parker, Terence Stamp, Amr Waked, Idris Elba, Jessica Brown Findlay, Jeremy Irvine, Thandie Newton, Tilda Swinton, Ralph Fiennes, Rebel Wilson, Eloise Mumford, Leslie Mann, Matthias Schoenaerts, Jennifer Ehle, Alison Brie, Tom Cullen, Elizabeth Debicki, Henry Cavill, Clint Dyer, Annabelle Wallis, Alicia Vikander, Noel Fisher, Jon Voight, Gabriel Basso, Will Arnett, Lia Marie Johnson, Kristen Wiig, Robin Williams, Jon Daly, Jeff Kahn, Jerry Stiller, Kathryn Hahn, Dick Van Dyke, Robert Downey Jr., Malin Akerman, Rooney Mara, Blake Lively, Andrew Garfield, Abigail Breslin, Kristen Stewart, Common, Emma Stone, Dave Franco, Michael Kenneth Williams, Kate Winslet, Lucy Walters, Kevin Bacon, Seth Rogen, Jeff Daniels, Marion Cotillard, Andreas Wisniewski, Charlize Theron, Florence Clery, Noomi Rapace, Dominic West, Nicholas Hoult, Frank Madigan, Logan Marshall-Green, James Badge Dale, Jack Madigan, Jeremy Irons, Michael Cera, Max Minghella, Liv Tyler, Evan Rachel Wood, Callum Keith Rennie, Joseph Gordon-Levitt, Jennifer Garner, Ken Watanabe, Rainn Wilson, Zach Galifianakis, Joaquin Phoenix, Chatchawai Kamonsakpitak, Paul Newman, Aasif Mandvi, Ross Kimball, Josh Brolin, Lake Bell, Kurt Fuller, Pierce Brosnan, Katherine Waterston, Bonnie Hunt, Emily Mortimer, Vince Vaughn, Larry the Cable Guy, Kathy Bates, Rob Corddry, Kate Upton, Matthew Morrison, Ellie Kemper, Dennis Quaid, Nikolaj Coster-Waldau, J. Todd Smith, Quvenzhane Wallis, Jason Segel, Jared Harris, Naomie Harris, Sean Penn, Adele Exarchopoulos, Jasmine Trinca, Tommy Lee Jones, Richard Jenkins, Jonah Hill, Sacha Baron Cohen, Mary Steenburgen, Linda Cardellini, Tina Fey, Derek Jeter, Kevin Hart, Eva Mendes, Elizabeth Banks, T.I., Thomas Haden Church, Gary Cole, John C. Reilly, Kevin Spacey, Kate Bosworth, Aaron Yoo, Dana Fuchs, Joe Anderson, Anthony Hopkins, Jennifer Connelly, Golshifteh Farahani, Matt Bomer, Max von Sydow, Angourie Rice, Abbie Cornish, Emma Watson, Denzel Washington, Albert Finney, Bill Paxton, Riz Ahmed, Jared Leto, Olivia Munn, Naomi Watts, Seth MacFarlane, Keri Russell, Ryoko Seta, Art Parkinson, Reese Witherspoon, Alexis Dziena, Mahershala Ali, Alex Pettyfer, Gugu Mbatha-Raw, Margot Robbie, Corey Stoll, Bryce Dallas Howard, Edgar Ramirez, Jerry Ferrara, Kevin Dillon, Kevin Connolly, Jacob Tremblay, Dan Stevens, Charlie Heaton, Kerry Bishe, Rebecca Ferguson, Anna Kendrick, Lisa Thoreson, Matt Damon, Benicio Del Toro, Haley Bennett, Jon Bernthal, Justin Theroux, Paul Dano, Florence Kastriner, Chris Cooper, Melanie Laurent, Alfred Molina, Judah Lewis, Viola Davis, Michael Pena, Anthony Edwards, Sarah Gadon, Oona Laurence, Isabella Rossellini, Vera Farmiga, Forest Whitaker, Gemma Arterton, America Ferrera, Stellan Skarsgard, Liam Neeson, Jessica Barth, Kate Mara, Isabelle Nelisse, Michael Stuhlbarg, Hunter McCracken, Megan Charpentier, Ty Simpkins, Charlie Day, Jennifer Aniston, Danny McBride, Emma Roberts, Josh Gad, Maya Rudolph, Ed Helms, Jordan Carlos, Margarita Levieva, Steve Wiebe, Julia Roberts, Andy Serkis, Joel Kinnaman, Kodi Smit-McPhee, Michael Keaton, Mila Kunis, Ray Stevenson, Gal Gadot, Ryan Reynolds, Taylor Swift, Jason Schwartzman, Bill Murray, George Clooney, Brenton Thwaites, Jeff Bridges, Simon Helberg, Hugh Grant, Ruben Blades, Zoey Deutch, Aubrey Plaza, Anna Friel, Usher Raymond, Jacki Weaver, Edie Falco, Danny DeVito, Zac Efron, Jenna Elfman, Elijah Wood, Rila Fukushima, Brittany Murphy, Halle Berry, Levi Miller, Shea Adams, Anthony Mackie, Sean Patrick Thomas, Ellen Burstyn, Danny Huston, Patrick Stewart, Liev Schreiber, Will Yun Lee, Tao Okamoto, Taron Egerton, Tom Costello, Famke Janssen, Dev Patel, Ian McKellen, Nicole Kidman, Eddie Baroo, Dakota Goyo, Jo Hartley, Garrett Hedlund, Evangeline Lilly, Will Poulter, Zoe Kravitz, Emily Browning, James Gandolfini, Kelly Adams, Olivia Colman, Ruth Wilson, Katy Barker, Luing Andrews, Paul Anderson, Til Schweiger, Domhnall Gleeson, Lynsey Taylor Mackay, Robert Redford, Dougie McConnell, Julianne Moore, Jon Favreau, Tony Danza, Jeremy McWilliams, Sebastian Stan, Renee Zellweger, Gemma Jones, Sally Phillips, Emory Cohen, Robert Carlyle, Brian Geraghty, Scott Glenn, Edward Norton, Paula Patton, Harold Perrineau, Simon Pegg, Jae Head, Ginnifer Goodwin, Will Smith, T.J. Miller, Jenny Slate, Aidan Turner, Ben Foster, Theo James, Vicky Krieps, Elizabeth Berrington, Martin Stringer, Katey Sagal, Daniel Day-Lewis, Miles Teller, Colin Farrell, Isla Fisher, Pierre Coffin, Sandra Bullock, Sam Trammell, Daniel Radcliffe, Toni Collette, Bryan Cranston, Chris Messina, Neil Patrick Harris, J.K. Simmons, Elle Fanning, Alan Arkin, Tyler Perry, John Goodman, Walton Goggins, Mary McCormack, Nathan Phillips, Rachel Bilson, Elizabeth Olsen, Jennifer Jason Leigh, Julianna Margulies, Hayden Christensen, Rachel Blanchard, Hayley Atwell, Kurt Russell, Paul Birchard, Hugo Weaving, John Cusack, Zac Mattoon O'Brien, Rupert Friend, Harrison Ford, Chloe Grace Moretz, Christopher Lee, David Thewlis, Mathieu Amalric, Christoph Waltz, Ben Walker, Christopher Plummer, Dakota Blue Richards, Lea Seydoux, Ethan Hawke, David Wenham, Adelaide Kane, Karl Urban, Olivia Thirlby, Max Burkholder, Patrick Wilson, Richard Dreyfuss, Rachel Wood, Ray Winstone, Bob Balaban, Paul Giamatti, Michelle Rodriguez, Ron Perlman, Diego Luna, Vin Diesel, John Boyega, Daisy Ridley, Sonoya Mizuno, Diane Lane, Jesse Plemons, Philip Seymour Hoffman, James Marsden, Patrick Dempsey, Susan Sarandon, Lily Cole, Jane Fonda, Harvey Keitel, Taylor Kitsch, Jack Nicholson, Zooey Deschanel, John Leguizamo, Joel McHale, Emile Hirsch, Danny Glover, Jack Reynor, Jessica Lange, Tony Shalhoub, Ashlyn Sanchez, Nicola Peltz, Rhona Mitra, James DuMont, Douglas M. Griffin, Stanley Tucci, Ashton Kutcher, Rasmus Hardiker, Vincent Cassel, Winona Ryder, Cary Elwes, Peter Sarsgaard, Greta Gerwig, Kevin Kline, Billy Crudup, James Franco, Gael Garcia Bernal, Julia Ormond, Richard Armitage, Jay Baruchel, Craig Ferguson, Kyle Chandler, Sarah Paulson, Karen Allen, Alec Baldwin, Martin Freeman, Sally Hawkins, Mohamed Akhzam, Imogen Poots, Alia Shawkat, Valerie Mahaffey, Tom Hanks, Laura Linney, Felicity Jones, Anna Faris, Neel Sethi, Natalie Martinez, Anthony LaPaglia, Toby Kebbell, Lewis MacDougall, Michael Ealy, Josh Hutcherson, Sam Rockwell, Liam Hemsworth, Rosario Dawson, Christopher Walken, Laurence Fishburne, Michael Sheen, Isaiah Stone, John Hawkes, Garret Dillahunt, Dylan Minnette, Greg Kinnear, Miranda Cosgrove, Ed Oxenbould, Julie Andrews, Russell Brand, Benjamin Bratt, Teresa Palmer, Luke Bracey, Mandy Gonzalez, Jason Flemyng, Romain Duris, Oona Chaplin, Guillaume Baillargeon, Emilie Leclerc, Camille Cottin, Kelly Reilly, Jalil Lespert, Tom Hughes, Barry Ward, Rachael Harris, Devon Bostick, Zachary Gordon, Robert Capron, Michelle Williams, Lucas Hedges, Sam Shepard, Faith Wladyka, Craig Van Hook, Frank Langella, John Doman, Albert Brooks, Lily Rabe, David Strathairn, Rosemarie DeWitt, Giovanni Ribisi, Shailene Woodley, Justin Bartha, Leslie Bibb, Jessica Biel, Sienna Miller, Brooke Shields, Vinnie Jones, Cole Konis, Daniel Bruhl, Riccardo Scamarcio, Kyle Gallner, Daniella Kertesz, Vincent Ebrahim, Logan Lerman, Robin Wright, Michael Mantell, Diane Kruger, Eli Roth, Mireille Enos, Michael B. Jordan, Eddie Marsan, Charlotte Gainsbourg, Willem Dafoe, Robert Pattinson, Tom Holland, Rinko Kikuchi, Luke Evans, Leonard Nimoy, Dean Norris, Joseph Mawle, Daniel Olbrychski, Amanda Peet, Anika Noni Rose, Bill Nighy, Lydia Wilson, Gil Birmingham, Ethan Suplee, Timothy Olyphant, Josh Duhamel, David Acord, Clifton Collins Jr., Gabriel Luna, Max Irons, Jake Abel, Gwyneth Paltrow, Melissa McCarthy, Julian Barratt, Essie Davis, Amber Heard, Kyra Sedgwick, Brittany Snow, Haley Lu Richardson, Connie Nielsen, Blake Jenner, Christopher Mintz-Plasse, Jim Carrey, Garrett M. Brown, Nicolas Cage, Milla Jovovich, Anya Taylor-Joy, Danny Sapani, Jessica Sula, Taraji P. Henson, Octavia Spencer, Dane Cook, Demi Moore, William Hurt, Janelle Monae, Nicholas Galitzine, Fionn O'Shea, Moe Dunford, Jessica Barden, Lupita Nyong'o, Carmen Ejogo, Madina Nalwanga, Tim Roth, Lorraine Toussaint, Martin Kabanza, Nick Frost, Werner Herzog, Colm Feore, Lesley Manville, Gattlin Griffith, Amy Ryan, Crispin Glover, Dolph Lundgren, Antonio Banderas, Paul Walker, Sylvester Stallone, Jet Li, Jessica Alba, Rosie Huntington-Whiteley, Odeya Rush, Ryan Lee, Julia Stiles, Cary-Hiroyuki Tagawa, Sarah Roemer, Richard Gere, Billy Bob Thornton, Maggie Grace, Auli'i Cravalho, Alexandra Daddario, Byung-hun Lee, Rachel House, Jordana Brewster, Danielle Nicolet, Adrianne Palicki, Colton Haynes, Temuera Morrison, Mauricio Lopez, Carla Gugino, Mickey Rourke, Stephen Dorff, James Hamrick, Alessandro Nivola, Rima Te Wiata, Julian Dennison, Rachael Blake, Bridgette Barrett, Jodie Foster, Joe Manganiello, De'Shawn Washington, Marlon Wayans, Laura Ramsey, Adewale Akinnuoye-Agbaje, Nick Offerman, Amanda Bynes, Damaine Radcliff, Jenna Dewan Tatum, Eddie Redmayne, Sean Bean, Ice Cube, Adam Rodriguez, Lois van Wijk, 50 Cent, Vincent D'Onofrio, Colm Meaney, Kerry Washington, Kylie Rogers, Brighton Sharbino, Barkhad Abdirahman, Marcia Gay Harden, Carrie-Anne Moss, Michael Chiklis, Stacy Martin, Riley Keough, David Morse, Sasha Lane, McCaul Lombardi, Charles Dance, Janet McTeer, Sam Claflin, Dakota Fanning, Don Cheadle, Carice van Houten, Kit Harington, Sarita Choudhury, Alexander Black, Jason O'Mara, Aiden Longworth, Michael McElhatton, Emma Fitzpatrick, Ari Graynor, Blythe Danner, John Cullum, Alice Eve, Bruce Boxleitner, Alexandra Maria Lara, Sean Bridgers, Wendy Crewson, Colin Quinn, Amy Schumer, Bill Hader, Josh Peck, Leehom Wang, Kristen Connolly, Isabel Lucas, Fran Kranz, Wei Tang, Anna Hutchison, Lin Shaye, Terry Crews, Lisa Kudrow, Jason Cope, Alice Braga, David James, Danila Kozlovsky, Nathalie Boltt, Rupert Grint, Brendan Fraser, Maria Bello, Scott Mescudi, Dominic Cooper, Steve Buscemi, Katie Holmes, Billy Crystal, Bella Heathcote, Jack Huston, Sam Riley, Freddie Crowder, Kiefer Sutherland, Rip Torn, Alexander Skarsgard, Topher Grace, Judy Davis, Zoe Kazan, Tadanobu Asano, Megan Park, Nellie, Rizwan Manji, Djimon Hounsou, Jonathan Roumie, Kagiso Kuypers, Christopher Fitzgerald, Katherine Heigl, Harry Connick Jr., Eric Winter, Bree Turner, Hilary Swank, Gretchen Mol, Chadwick Boseman, Maggie Q, Justin Long, Kara Hayward, Jared Gilman, Julianne Hough, Robert Knepper, Ving Rhames, Diego Boneta, Aldis Hodge, Cobie Smulders, Peter Dinklage, Adam Sandler, Kevin James, Orto Ignatiussen, Joely Richardson, Addison Timlin, Hermione Corfield, Jaden Smith, Brian Howe, Ezra Miller, Jasper Newell, Alden Ehrenreich, Adrien Brody, F. Murray Abraham, Anna Camp, Iris Apatow, Maude Apatow, Paul Rudd, Thomas Lennon, Matthew Perry, Keith Carradine, Duncan Duff, Cynthia Nixon, Tony Amendola, Ward Horton, Alfre Woodard, Ben Barnes, Keanu Reeves, Moises Arias, Nick Robinson, Peyton List, Calum Worthy, Logan Paul, Alistair Abell, Kate McKinnon, Leslie Jones, David Spade, Kristen Bell, Christina Applegate, Robert Duvall, Terrence Howard, Jackie Earle Haley, Sunny Pawar, Kathy Baker, Angelo Josue Lozano Corzo, ?scar Jaenada, Michiel Huisman, Brett Cullen, Rhys Ifans, Irrfan Khan, Alexander Ludwig, Logan Huffman, Wes Bentley, Sigrid Bouaziz, Taylor Lautner, Xavier Samuel, Anders Danielsen Lie, Lars Eidinger, Scott Lawrence, Sarah Clarke, Vernetta Lopez, Peter Facinelli, Billy Burke, Kat Dennings, Dan Byrd, Stephen Merchant, Colin Hanks, Penn Badgley, Miles Heizer, Emily Meade, Ansel Elgort, Randall Park, Mia Stallard, Craig Robinson, Gerry Bednob, Lizzy Caplan, Nathalie Baye, Christina Hendricks, Viggo Mortensen, Peter Stormare, Ewa Froling, Lena Endre, Michael Nyqvist, Jack O'Connell, Analeigh Tipton, John Malkovich, Emayatzy Corinealdi, Tammy Blanchard, John Krasinski, Pablo Schreiber, Max Martini, David Denman, Bruce Greenwood, Laura Dern, Raghuvir Joshi, Karolina Gruszka, Malcolm Sinclair, Kieran Culkin, Alison Pill, Mary Elizabeth Winstead, Juno Temple, Gemma Ward, Scott Speedman, Alex Fisher, Sally Field, Geoffrey Arend, Beverly D'Angelo, Robbie Amell, Cheryl Hines, Rose McGowan, Marley Shelton, Jemaine Clement, Freddy Rodriguez, Eric Stonestreet, Louis C.K., Kai Ryssdal, Olivia Williams, Ewan McGregor, Karen Moskow, Jason Barry, Dan Fogler, Alison Sudol, Joey Lauren Adams, Lucas Black, Antje Traue, Charles S. Dutton, Kenny Wormald, Paul Bettany, Cam Gigandet, Andie MacDowell, Aurelien Recoing, Salim Kechiouche, Matthew Fox, Cara Buono, Gregg Weiner, Steve Lantz, Craig T. Nelson, John Carroll Lynch, Amy Poehler, Ike Barinholtz, Sam Elliott, Matt Long, Nathan Fillion, Don Thompson, Michael Rooker, Josh Wiggins, Luke Kleintank, Lauren Graham, Salma Hayek, Toby Jones, Sarah Silverman, Jane Lynch, Jack McBrayer, Rosie Shaw, Brandon Routh, Dominique McElligott, Annabeth Gish, Thomas Jane, Jeffrey Dean Morgan, Trenton Rogers, Peter Riegert, Morgan Lily, Jena Malone, Vanessa Hudgens, Dermot Mulroney, Diego Klattenhoff, Richenda Carey, Michael Gambon, Dale Dickey, Nadine Velazquez, Jim Caviezel, Val Kilmer, David Harbour, Marton Csokas, Stephen Henderson, Jovan Adepo, Sophie Nelisse, Joe Cobden, Billie Piper, Cush Jumbo, James Floyd, Linh Dan Pham, Sarah Polley, James Frecheville, Josef Altin, Elisabeth Moss, Oaklee Pendergast, Michael Pitt, Brady Corbet, Armin Mueller-Stahl, Freddie Highmore, Jonathan Rhys Meyers, Gaby Hoffmann, Duan Sanderson, Shariff Earp, Alex R. Hibbert, Gabriella Wilde, Robert Patrick, Adrian Martinez, Eric Godon, Kristin Scott Thomas, Rodrigo Santoro, Michael Douglas, Oakes Fegley, Boyd Holbrook, Sheila Kelley, Maika Monroe, Joel David Moore, Adam Devine, James Ransone, Andy Lau, Tian Jing, Taissa Farmiga, Lily Collins, Steve Tom, Vincent Kartheiser, Antonia Ribero, Annabelle Attanasio, Nancy Kwan, Alice Englert, Catalina Sandino Moreno, Hayden Panettiere, Emma Thompson, Tessa Thompson, Sue Dahlman, Tijuana Ricks, CCH Pounder, Ron Livingston, Lili Taylor, Madison Wolfe, Isabelle Fuhrman, Frances O'Connor, Oprah Winfrey, Dominique Tipper, Paddy Considine, Glenn Close, Rihanna, Leland Orser, Brooklyn Decker, Aidan Quinn, January Jones, Michael Yare, Sean Bott, Amber Tamblyn, Rose Leslie, Andy Samberg, Katie Crown, Kelsey Grammer, Lauren Holly, Lucy Boynton, Kiernan Shipka, Jonathan Groff, Idina Menzel, Dax Shepard, Luke Wilson, Steele Stebbins, Skyler Gisondo, Karin Konoval, Freida Pinto, Ed Skrein, Morena Baccarin, Nick Krause, Raffey Cassidy, Amara Miller, Hugh Laurie, Britt Robertson, Rory Cochrane, Katee Sackhoff, Karen Gillan, Tangie Ambrose, Tyler Hoechlin, Nicholas Braun, Ryan Guzman, Cedric the Entertainer, Lucy Fry, Mateo Arias, Gabriel Byrne, Israel Broussard, Taylor Schilling, Emily Ratajkowski, Jonny Weston, Riley Thomas Stewart, ?lafur Darri ?lafsson, Jamal Woolard, Derek Luke, Momo Dione, Jackson Rathbone, Noah Ringer, Saurabh Shukla, Anil Kapoor, Audrey Tautou, Charlie Cox, Ken Stott, Claire Danes, Jean Reno, Arturo Castro, Miyavi, Mason Lee, Joe Alwyn, Kaya Scodelario, Dylan O'Brien, Thomas Brodie-Sangster, Paula Prentiss, Portia Doubleday, Bel Powley, Stephen Moyer, Tye Sheridan, Imelda Staunton, Rufus Sewell, Mo'Nique, Mariah Carey, Travis Fimmel, Gabourey Sidibe, Sanjeev Bhaskar, Kate Beckinsale, Rob Riggle, Tim McGraw, Quinton Aaron, Salli Richardson-Whitfield, Sophie Okonedo, Charlie Tahan, Adam Pally, Shannon Woodward, Thomas Middleditch, Jamie Chung, Scott Adsit, Mike Vogel, Ryan Potter, Jessica Lucas, Lara Pulver, Tobias Menzies, Paul Reiser, Melissa Benoist, Bokeem Woodbine, Annie Rose Buckley, Michael McDonald, Demian Bichir, Lewis Black, Eddie Izzard, Annette Bening, Carly Rae Jepsen, Karl Glusman, Joel Courtney, AJ Michalka, Dane DeHaan, Maddie Ziegler, John Gallagher Jr., Vanessa Ferlito, Danny Trejo, Zoe Bell, T.R. Knight, Nicole Beharie, Joshua Leonard, Matthew Zuk, Gabriela Lopez, Jamie Blackley, Bailey Anne Borders, Rory J. Saper, Christian Stevens, Edward Asner, Jordan Nagai, John Ratzenberger, Elijah Smith, Sarah Snook, Kari Matchett, Ellar Coltrane, Zachary Bennett, Madeleine West, Noah Taylor, Fred Dalton Thompson, Patricia Arquette, Juliet Rylance, Jordi Moll?, Wentworth Miller, Jerry O'Connell, Elisabeth Shue, Aryana Engineer, Sienna Guillory, Stephen Lang, Zachary Levi, Selma Blair, Doug Jones, Jason Momoa, Mandy Moore, Donna Murphy, John Alexander, Erin Moriarty, Mel Gibson, Michael Parks, Alan Tudyk, Donnie Yen, Arnaud Viard, Linda Gegusch, Samantha Morton, Lynn Collins, AnnaSophia Robb, Chris Wedge, Denis Leary, Ray Romano, Ophelia Lovibond, Brian Cox, Aidan Gillen, Ferdia Walsh-Peelo, Maria Doyle Kennedy, Steven Mackintosh, Selena Gomez, Nat Wolff, Alan Alda, Tim Allen, Mark Rylance, Ned Beatty, Joan Cusack, Tom Prior, Sophie Perry, Nazanin Boniadi, India Eisley, Stephen Rea, Bill Pullman, Jeff Goldblum, Jean-Claude Van Damme, Randy Couture, Lior Ashkenazi, Daniel Zovatto, Jane Levy, Olivia DeJonge, Deanna Dunagan, Peter McRobbie, Benjamin Walker, Gabriel Bateman, Andrew Simpson, Mia Goth, Martin McCann, Ellen DeGeneres, Kaitlin Olson, Ed O'Neill, Morgan Saylor, Brian Marc, Teyonah Parris, Tyler James Williams, Kevin McKidd, Steve Coogan, Brandon T. Jackson, Phylicia Rashad, Kati Outinen, Storm Acheche Sahlstrom, Alfie Allen, Moises Acevedo, Emilie de Ravin, Caitlyn Rund, Keith David, Bruno Campos, Alexis Clagett, David Lyons, Josh Lucas, Lorraine Nicholson, Daniel Eric Gold, Callan McAuliffe, Ella Anderson, Noah Wiseman, Daniel Henshall, Hayley McElhinney, Sean Faris, Tom Sizemore, Matt Lanter, Shawn Roberts, Ali Larter, Iain Glen, Kim Coates, Ralph Ineson, Kate Dickie, Julian Richings, Wenwen Han, Jackie Chan, Marisa Paredes, Jan Cornet, Elena Anaya, Milo Ventimiglia, Julie Benz, Antonio Tarver, Burt Young, Matthew Marsden, Graham McTavish, Scott Eastwood, Trey Songz, Tania Raymonde, Ji-min Han, Yoo Gong, Kang-ho Song, Thomas Mann, RJ Cyler, Olivia Cooke, Laurie Holden, Deborah Kara Unger, Radha Mitchell, Eve, Regina Hall, Anthony Anderson, Andre Braugher, Cary Joji Fukunaga, Jessie Ok Gray, Christian Cooke, Jaime Winstone, Teri Hatcher, Jennifer Saunders, John Hodgman, Mindy Kaling, Jennifer Koenig, Michael Dickson, Andrea Whitburn, Natasha Henstridge, Lukas Hassel, Dominique Swain, Jorge Garcia, Josh Brener, Andy Garcia, Ben Winchell, C.H. Evans, Sandra Kinder, Chris Isaak, Haley Joel Osment, Genesis Rodriguez, Drew Barrymore, Wendi McLendon-Covey, Nick Swardson, Emmanuelle Chriqui, Kevin Nealon, John Turturro, Chris Rock, Lucas Till, Barry Pepper, Kim Cattrall, Kristin Davis, Sarah Jessica Parker, Ana de Armas, Christopher McDonald, Mira Sorvino, Aaron Burns, Lorenza Izzo, Suraj Sharma, Adil Hussain, Tabu, Eddie Murphy, Chloe Sevigny, Natascha McElhone, Emma Greenwell, Kathleen Quinlan, Ted Levine, George MacKay, Annalise Basso, Samantha Isler, Christian Distefano, Laura Allen, Andy Powers, Michael Kelly, Travis Tope, Sofia Black-D'Elia, Tyne Daly, Max Greenfield, Mae Whitman, Allison Janney, Bella Thorne, Cori Gonzalez-Macuer, Taika Waititi, Ruby Barnhill, Jonny Brugh, Penelope Wilton, Shad Moss, Damien Marzette, Zachery Ty Bryan, Akiva Schaffer, Jorma Taccone, Ashley Benson, Rachel Korine, Ronnie Gene Blevins, Michael Vartan, Victoria Justice, Steven Yeun, Brit Marling, Astrid Berges-Frisbey, Olivia Luccardi, Lili Sepe, Keir Gilchrist, Jemima West, Jamie Campbell Bower, Robert Sheehan, Julie Walters, Kelly Macdonald, Billy Connolly, Jim Parsons, Jennifer Lopez, Steve Martin, Kristin Chenoweth, John Corbett, Laurent Lucas, Pierre Niney, Lambert Wilson, Giancarlo Esposito, Joey Morgan, Logan Miller, Sarah Dumont, Mel Raido, Duncan Joiner, Damon Wayans Jr., Nina Dobrev, Jake Johnson, Shiloh Fernandez, Lou Taylor Pucci, Gabriel Chavarria, Tony Revolori, Theo Rossi, Juan Saavedra, Aomi Muyock, Klara Kristin, Jason Isaacs, Ivo Nandi, Michael Trucco, John C. McGinley, Samantha Sloyan, Adria Arjona, Tony Goldwyn, Kate Siegel, Mark Chao, Dave Bautista, Ni Ni, Cara Delevingne, Austin Abrams, Justice Smith, Gina Carano, Alain Moussi, Carmen Electra, Vanessa Lachey, Nicole Parker, Dong-seok Ma, Soo-an Kim, Yu-mi Jung, Hae-il Park, Doona Bae, Hee-Bong Byun, Dax Flame, Oliver Cooper, Jonathan Daniel Brown, Kirby Bliss Blanton, Ariel Levy, Elizabeth Reaser, Henry Thomas, Lulu Wilson, Bill Engvall, Alex Essoe, Josh Stewart, Lainie Kazan, Nia Vardalos, Michael Constantine, Ella Rumpf, Garance Marillier, Rabah Nait Oufella, Paula Beer, Ernst Stotzner, Marie Gruber, Shameik Moore, Kiersey Clemons, Kimberly Elise
"""
OTHER_ANS_Q7 = """50 Cent
?lafur Darri ?lafsson
?scar Jaenada
AJ Michalka
Aaron Burns
Aaron Eckhart
Aaron Paul
Aaron Taylor-Johnson
Aaron Yoo
Aasif Mandvi
Abbie Cornish
Abigail Breslin
Adam Brody
Adam Devine
Adam Driver
Adam Levine
Adam Pally
Adam Rodriguez
Adam Sandler
Addison Timlin
Adelaide Kane
Adele Exarchopoulos
Adewale Akinnuoye-Agbaje
Adil Hussain
Adria Arjona
Adrian Grenier
Adrian Martinez
Adrianne Palicki
Adrien Brody
Aidan Gillen
Aidan Quinn
Aidan Turner
Aiden Longworth
Akiva Schaffer
Alain Moussi
Alan Alda
Alan Arkin
Alan Rickman
Alan Tudyk
Albert Brooks
Albert Finney
Alden Ehrenreich
Aldis Hodge
Alec Baldwin
Alessandro Nivola
Alex Essoe
Alex Fisher
Alex Pettyfer
Alex R. Hibbert
Alexander Black
Alexander Ludwig
Alexander Skarsgard
Alexandra Daddario
Alexandra Maria Lara
Alexis Clagett
Alexis Dziena
Alfie Allen
Alfre Woodard
Alfred Molina
Ali Larter
Alia Shawkat
Alice Braga
Alice Englert
Alice Eve
Alicia Vikander
Alison Brie
Alison Pill
Alison Sudol
Alistair Abell
Allen Leech
Allison Janney
Allison Tolman
Amanda Bynes
Amanda Peet
Amanda Seyfried
Amara Miller
Amber Heard
Amber Tamblyn
America Ferrera
Amr Waked
Amy Adams
Amy Poehler
Amy Ryan
Amy Schumer
Ana de Armas
Analeigh Tipton
Anders Danielsen Lie
Anders Holm
Andie MacDowell
Andre Braugher
Andrea Riseborough
Andrea Whitburn
Andreas Wisniewski
Andrew Garfield
Andrew Scott
Andrew Simpson
Andy Garcia
Andy Lau
Andy Powers
Andy Samberg
Andy Serkis
Ang Phula Sherpa
Angela Bassett
Angelina Jolie
Angelo Josue Lozano Corzo
Angourie Rice
Anika Noni Rose
Anil Kapoor
Anna Camp
Anna Faris
Anna Friel
Anna Hutchison
Anna Kendrick
AnnaSophia Robb
Annabelle Attanasio
Annabelle Wallis
Annabeth Gish
Annalise Basso
Anne Hathaway
Annette Bening
Annie Rose Buckley
Ansel Elgort
Anthony Anderson
Anthony Edwards
Anthony Hopkins
Anthony LaPaglia
Anthony Mackie
Antje Traue
Anton Yelchin
Antonia Ribero
Antonio Banderas
Antonio Tarver
Anya Taylor-Joy
Aomi Muyock
Ari Graynor
Ariel Levy
Armie Hammer
Armin Mueller-Stahl
Arnaud Viard
Arnold Schwarzenegger
Art Parkinson
Arturo Castro
Aryana Engineer
Asa Butterfield
Ashley Benson
Ashlyn Sanchez
Ashton Kutcher
Astrid Berges-Frisbey
Aubrey Plaza
Audrey Tautou
Auli'i Cravalho
Aurelien Recoing
Austin Abrams
Austin Stowell
Bailey Anne Borders
Barkhad Abdi
Barkhad Abdirahman
Barry Pepper
Barry Ward
Bel Powley
Bella Heathcote
Bella Thorne
Ben Affleck
Ben Barnes
Ben Foster
Ben Kingsley
Ben Stiller
Ben Walker
Ben Whishaw
Ben Winchell
Benedict Cumberbatch
Benedict Wong
Benicio Del Toro
Benjamin Bratt
Benjamin Walker
Beverly D'Angelo
Bill Engvall
Bill Hader
Bill Murray
Bill Nighy
Bill Paxton
Bill Pullman
Billie Piper
Billy Bob Thornton
Billy Burke
Billy Connolly
Billy Crudup
Billy Crystal
Blake Jenner
Blake Lively
Blythe Danner
Bob Balaban
Bokeem Woodbine
Bonnie Hunt
Boyd Holbrook
Brad Pitt
Bradley Cooper
Brady Corbet
Brandon Routh
Brandon T. Jackson
Bree Turner
Brenda Blethyn
Brendan Fraser
Brendan Gleeson
Brenton Thwaites
Brett Cullen
Brian Caspe
Brian Cox
Brian Dennehy
Brian Geraghty
Brian Howe
Brian Marc
Bridgette Barrett
Brie Larson
Brighton Sharbino
Brit Marling
Britt Robertson
Brittany Murphy
Brittany Snow
Brooke Shields
Brooklyn Decker
Bruce Boxleitner
Bruce Greenwood
Bruce Willis
Bruno Campos
Bryan Cranston
Bryan Greenberg
Bryce Dallas Howard
Burt Young
Byung-hun Lee
C.H. Evans
CCH Pounder
Caitlyn Rund
Callan McAuliffe
Callum Keith Rennie
Calum Worthy
Cam Gigandet
Cameron Diaz
Camille Cottin
Candice Bergen
Cara Buono
Cara Delevingne
Carey Mulligan
Carice van Houten
Carla Gugino
Carly Rae Jepsen
Carmen Ejogo
Carmen Electra
Carrie-Anne Moss
Cary Elwes
Cary Joji Fukunaga
Cary-Hiroyuki Tagawa
Casey Affleck
Catalina Sandino Moreno
Cate Blanchett
Catherine Keener
Cedric the Entertainer
Chadwick Boseman
Channing Tatum
Charles Dance
Charles S. Dutton
Charlie Cox
Charlie Day
Charlie Heaton
Charlie Hunnam
Charlie Tahan
Charlize Theron
Charlotte Gainsbourg
Charlotte Le Bon
Chatchawai Kamonsakpitak
Cheryl Hines
Chiwetel Ejiofor
Chloe Grace Moretz
Chloe Sevigny
Chris Cooper
Chris Evans
Chris Hemsworth
Chris Isaak
Chris Messina
Chris Pine
Chris Pratt
Chris Rock
Chris Wedge
Christian Bale
Christian Cooke
Christian Distefano
Christian Stevens
Christian Stolte
Christina Applegate
Christina Hendricks
Christoph Waltz
Christopher Evan Welch
Christopher Fitzgerald
Christopher Lee
Christopher McDonald
Christopher Mintz-Plasse
Christopher Plummer
Christopher Walken
Ciaran Hinds
Cillian Murphy
Claire Danes
Clifton Collins Jr.
Clint Dyer
Clive Owen
Cobie Smulders
Cole Konis
Colin Farrell
Colin Firth
Colin Hanks
Colin Quinn
Colm Feore
Colm Meaney
Colton Haynes
Common
Connie Nielsen
Corey Stoll
Cori Gonzalez-Macuer
Craig Ferguson
Craig Robinson
Craig T. Nelson
Craig Van Hook
Crispin Glover
Cush Jumbo
Cynthia Nixon
Daisy Ridley
Dakota Blue Richards
Dakota Fanning
Dakota Goyo
Dakota Johnson
Dale Dickey
Damaine Radcliff
Damien Marzette
Damon Wayans Jr.
Dan Byrd
Dan Fogler
Dan Stevens
Dana Fuchs
Dane Cook
Dane DeHaan
Daniel Bruhl
Daniel Craig
Daniel Day-Lewis
Daniel Eric Gold
Daniel Gimenez Cacho
Daniel Henshall
Daniel Olbrychski
Daniel Radcliffe
Daniel Zovatto
Daniella Kertesz
Danielle Nicolet
Danila Kozlovsky
Danny DeVito
Danny Glover
Danny Huston
Danny McBride
Danny Sapani
Danny Trejo
Dave Bautista
Dave Franco
David Acord
David Denman
David Harbour
David James
David Lyons
David Morse
David Oyelowo
David Spade
David Strathairn
David Thewlis
David Wenham
Dax Flame
Dax Shepard
De'Shawn Washington
Dean Mumford
Dean Norris
Deanna Dunagan
Deborah Kara Unger
Demi Moore
Demian Bichir
Denis Leary
Dennis Quaid
Denzel Washington
Derek Jacobi
Derek Jeter
Derek Luke
Dermot Mulroney
Dev Patel
Devon Bostick
Diane Kruger
Diane Lane
Dianna Agron
Dick Van Dyke
Diego Boneta
Diego Klattenhoff
Diego Luna
Djimon Hounsou
Dolph Lundgren
Domhnall Gleeson
Dominic Cooper
Dominic West
Dominique McElligott
Dominique Swain
Dominique Tipper
Don Cheadle
Don Thompson
Donald Sutherland
Dong-seok Ma
Donna Murphy
Donnie Yen
Doona Bae
Doug Jones
Dougie McConnell
Douglas M. Griffin
Drew Barrymore
Duan Sanderson
Duncan Duff
Duncan Joiner
Dustin Hoffman
Dwayne Johnson
Dylan Minnette
Dylan O'Brien
Ed Harris
Ed Helms
Ed O'Neill
Ed Oxenbould
Ed Skrein
Eddie Baroo
Eddie Izzard
Eddie Marsan
Eddie Murphy
Eddie Redmayne
Edgar Ramirez
Edie Falco
Edward Asner
Edward Norton
Elena Anaya
Eli Roth
Elijah Smith
Elijah Wood
Elisabeth Moss
Elisabeth Shue
Elizabeth Banks
Elizabeth Berrington
Elizabeth Debicki
Elizabeth Olsen
Elizabeth Reaser
Ella Anderson
Ella Rumpf
Ellar Coltrane
Elle Fanning
Ellen Burstyn
Ellen DeGeneres
Ellen Page
Ellie Kemper
Eloise Mumford
Emayatzy Corinealdi
Emile Hirsch
Emilia Clarke
Emilie Leclerc
Emilie de Ravin
Emily Blunt
Emily Browning
Emily Meade
Emily Mortimer
Emily Ratajkowski
Emma Fitzpatrick
Emma Greenwell
Emma Roberts
Emma Stone
Emma Thompson
Emma Watson
Emmanuelle Chriqui
Emory Cohen
Eric Bana
Eric Godon
Eric Stonestreet
Eric Winter
Erin Moriarty
Ernst Stotzner
Essie Davis
Ethan Hawke
Ethan Suplee
Eva Green
Eva Mendes
Evan Rachel Wood
Evangeline Lilly
Eve
Ewa Froling
Ewan McGregor
Ewen Leslie
Ezra Miller
F. Murray Abraham
Faith Wladyka
Famke Janssen
Felicity Jones
Ferdia Walsh-Peelo
Fionn O'Shea
Florence Clery
Florence Kastriner
Forest Whitaker
Fran Kranz
Frances O'Connor
Francesc Albiol
Frank Langella
Frank Madigan
Fred Dalton Thompson
Freddie Crowder
Freddie Highmore
Freddy Rodriguez
Freida Pinto
Gabourey Sidibe
Gabriel Basso
Gabriel Bateman
Gabriel Byrne
Gabriel Chavarria
Gabriel Luna
Gabriela Lopez
Gabriella Wilde
Gaby Hoffmann
Gael Garcia Bernal
Gal Gadot
Garance Marillier
Garret Dillahunt
Garrett Hedlund
Garrett M. Brown
Gary Cole
Gary Oldman
Gattlin Griffith
Gemma Arterton
Gemma Jones
Gemma Ward
Genesis Rodriguez
Geoffrey Arend
Geoffrey Rush
George Clooney
George Lopez
George MacKay
Gerard Butler
Gerry Bednob
Giancarlo Esposito
Gil Birmingham
Gina Carano
Ginnifer Goodwin
Giovanni Ribisi
Glenn Close
Golshifteh Farahani
Graham McTavish
Greg Kinnear
Gregg Weiner
Greta Gerwig
Gretchen Mol
Gugu Mbatha-Raw
Guillaume Baillargeon
Guy Pearce
Gwyneth Paltrow
Hae-il Park
Hailee Steinfeld
Haley Bennett
Haley Joel Osment
Haley Lu Richardson
Halle Berry
Hans Matheson
Harley Quinn Smith
Harold Perrineau
Harrison Ford
Harry Connick Jr.
Harvey Keitel
Hayden Christensen
Hayden Panettiere
Hayley Atwell
Hayley McElhinney
Heath Ledger
Hee-Bong Byun
Helen Mirren
Helena Bonham Carter
Henry Cavill
Henry Thomas
Hermione Corfield
Hilary Swank
Hugh Grant
Hugh Jackman
Hugh Laurie
Hugo Weaving
Hunter McCracken
Iain Glen
Ian McKellen
Ian McShane
Ice Cube
Idina Menzel
Idris Elba
Ike Barinholtz
Imelda Staunton
Imogen Poots
India Eisley
Iris Apatow
Irrfan Khan
Isabel Lucas
Isabella Rossellini
Isabelle Fuhrman
Isabelle Nelisse
Isaiah Stone
Isla Fisher
Israel Broussard
Ivo Nandi
J. Todd Smith
J.K. Simmons
Jack Black
Jack Davenport
Jack Huston
Jack Madigan
Jack McBrayer
Jack Nicholson
Jack O'Connell
Jack Reynor
Jacki Weaver
Jackie Chan
Jackie Earle Haley
Jackson Rathbone
Jacob Tremblay
Jaden Smith
Jae Head
Jai Courtney
Jaime Winstone
Jake Abel
Jake Gyllenhaal
Jake Johnson
Jalil Lespert
Jamal Woolard
James Badge Dale
James DuMont
James Floyd
James Franco
James Frecheville
James Gandolfini
James Hamrick
James Marsden
James McAvoy
James Ransone
Jamie Bell
Jamie Blackley
Jamie Campbell Bower
Jamie Chung
Jamie Dornan
Jamie Foxx
Jan Cornet
Jane Fonda
Jane Levy
Jane Lynch
Janelle Monae
Janet McTeer
January Jones
Jared Gilman
Jared Harris
Jared Leto
Jasmine Trinca
Jason Barry
Jason Bateman
Jason Clarke
Jason Cope
Jason Flemyng
Jason Isaacs
Jason Momoa
Jason O'Mara
Jason Schwartzman
Jason Segel
Jason Statham
Jason Sudeikis
Jasper Newell
Javier Bardem
Jay Baruchel
Jean Reno
Jean-Claude Van Damme
Jeff Bridges
Jeff Daniels
Jeff Goldblum
Jeff Kahn
Jeffrey Dean Morgan
Jeffrey Wright
Jemaine Clement
Jemima West
Jena Malone
Jenna Dewan Tatum
Jenna Elfman
Jennifer Aniston
Jennifer Connelly
Jennifer Ehle
Jennifer Garner
Jennifer Jason Leigh
Jennifer Koenig
Jennifer Lawrence
Jennifer Lopez
Jennifer Morrison
Jennifer Saunders
Jenny Slate
Jeremy Davies
Jeremy Irons
Jeremy Irvine
Jeremy McWilliams
Jeremy Renner
Jerry Ferrara
Jerry O'Connell
Jerry Stiller
Jesse Eisenberg
Jesse Plemons
Jessica Alba
Jessica Barden
Jessica Barth
Jessica Biel
Jessica Brown Findlay
Jessica Chastain
Jessica Lange
Jessica Lucas
Jessica Sula
Jessie Ok Gray
Jet Li
Ji-min Han
Jim Broadbent
Jim Carrey
Jim Caviezel
Jim Parsons
Jim Sturgess
Jo Hartley
Joan Allen
Joan Cusack
Joaquin Phoenix
Jodie Foster
Joe Alwyn
Joe Anderson
Joe Cobden
Joe Manganiello
Joel Courtney
Joel David Moore
Joel Edgerton
Joel Kinnaman
Joel McHale
Joely Richardson
Joey Lauren Adams
Joey Morgan
John Alexander
John Boyega
John C. McGinley
John C. Reilly
John Carroll Lynch
John Corbett
John Cullum
John Cusack
John D'Leo
John Doman
John Gallagher Jr.
John Goodman
John Hawkes
John Hodgman
John Hurt
John Krasinski
John Leguizamo
John Malkovich
John Ratzenberger
John Travolta
John Turturro
Johnny Simmons
Jon Bernthal
Jon Daly
Jon Favreau
Jon Hamm
Jon Voight
Jonah Hill
Jonathan Daniel Brown
Jonathan Groff
Jonathan Rhys Meyers
Jonathan Roumie
Jonny Brugh
Jonny Weston
Jordan Carlos
Jordan Nagai
Jordana Brewster
Jordi Moll?
Jorge Garcia
Jorma Taccone
Josef Altin
Joseph Fiennes
Joseph Gordon-Levitt
Joseph Mawle
Josh Brener
Josh Brolin
Josh Duhamel
Josh Gad
Josh Hartnett
Josh Hutcherson
Josh Lucas
Josh Peck
Josh Stewart
Josh Wiggins
Joshua Leonard
Jovan Adepo
Juan Saavedra
Judah Lewis
Jude Law
Judi Dench
Judy Davis
Judy Greer
Julia Ormond
Julia Roberts
Julia Stiles
Julian Barratt
Julian Dennison
Julian Richings
Julianna Margulies
Julianne Hough
Julianne Moore
Julie Andrews
Julie Benz
Julie Walters
Juliet Rylance
Juno Temple
Justice Smith
Justin Bartha
Justin Long
Justin Theroux
Justin Timberlake
Kagiso Kuypers
Kai Ryssdal
Kaitlin Olson
Kang-ho Song
Kara Hayward
Karel Hermanek Jr.
Karen Allen
Karen Disher
Karen Gillan
Karen Moskow
Kari Matchett
Karin Konoval
Karl Glusman
Karl Urban
Karolina Gruszka
Kat Dennings
Kate Beckinsale
Kate Bosworth
Kate Dickie
Kate Hudson
Kate Mara
Kate McKinnon
Kate Siegel
Kate Upton
Kate Winslet
Katee Sackhoff
Katey Sagal
Katherine Heigl
Katherine Waterston
Kathleen Quinlan
Kathryn Hahn
Kathy Baker
Kathy Bates
Kati Outinen
Katie Crown
Katie Holmes
Katy Barker
Kaya Scodelario
Keanu Reeves
Keir Gilchrist
Keira Knightley
Keith Carradine
Keith David
Kelly Adams
Kelly Macdonald
Kelly Reilly
Kelsey Grammer
Ken Stott
Ken Watanabe
Kenneth Branagh
Kenny Wormald
Keri Russell
Kerry Bishe
Kerry Washington
Kevin Bacon
Kevin Connolly
Kevin Costner
Kevin Dillon
Kevin Hart
Kevin James
Kevin Kline
Kevin McKidd
Kevin Nealon
Kevin Spacey
Kiefer Sutherland
Kieran Culkin
Kiernan Shipka
Kiersey Clemons
Kim Cattrall
Kim Coates
Kimberly Elise
Kirby Bliss Blanton
Kirsten Dunst
Kit Harington
Klara Kristin
Kodi Smit-McPhee
Kristen Bell
Kristen Connolly
Kristen Stewart
Kristen Wiig
Kristin Chenoweth
Kristin Davis
Kristin Scott Thomas
Kurt Fuller
Kurt Russell
Kyle Chandler
Kyle Gallner
Kylie Rogers
Kyra Sedgwick
Lainie Kazan
Lake Bell
Lambert Wilson
Lara Pulver
Larry the Cable Guy
Lars Eidinger
Laura Allen
Laura Dern
Laura Linney
Laura Ramsey
Lauren Graham
Lauren Holly
Laurence Fishburne
Laurent Lucas
Laurie Holden
Lea Seydoux
Leehom Wang
Leland Orser
Lena Endre
Lena Headey
Leonard Nimoy
Leonardo DiCaprio
Lesley Manville
Leslie Bibb
Leslie Jones
Leslie Mann
Levi Miller
Lewis Black
Lewis MacDougall
Lia Marie Johnson
Liam Hemsworth
Liam Neeson
Liana Liberato
Liev Schreiber
Lili Sepe
Lili Taylor
Lily Cole
Lily Collins
Lily James
Lily Rabe
Lily-Rose Depp
Lin Shaye
Linda Cardellini
Linda Gegusch
Linh Dan Pham
Lior Ashkenazi
Lisa Kudrow
Lisa Thoreson
Liv Tyler
Lizzy Caplan
Logan Huffman
Logan Lerman
Logan Marshall-Green
Logan Miller
Logan Paul
Lois van Wijk
Lorenza Izzo
Lorraine Nicholson
Lorraine Toussaint
Lou Taylor Pucci
Louis C.K.
Lucas Black
Lucas Hedges
Lucas Till
Lucy Boynton
Lucy Fry
Lucy Liu
Lucy Walters
Luing Andrews
Lukas Hassel
Luke Bracey
Luke Evans
Luke Kleintank
Luke Wilson
Lulu Wilson
Lupita Nyong'o
Lydia Wilson
Lynn Collins
Lynsey Taylor Mackay
Mackenzie Foy
Maddie Ziegler
Madeleine West
Madina Nalwanga
Madison Wolfe
Mae Whitman
Maggie Grace
Maggie Gyllenhaal
Maggie Q
Mahershala Ali
Maika Monroe
Malcolm Sinclair
Malin Akerman
Mandy Gonzalez
Mandy Moore
Marcia Gay Harden
Margarita Levieva
Margot Robbie
Maria Bello
Maria Dizzia
Maria Doyle Kennedy
Mariah Carey
Marie Gruber
Marion Cotillard
Marisa Paredes
Mark Chao
Mark Ruffalo
Mark Rylance
Mark Strong
Mark Wahlberg
Marley Shelton
Marlon Wayans
Martin Freeman
Martin Henderson
Martin Kabanza
Martin McCann
Martin Stringer
Marton Csokas
Mary Elizabeth Winstead
Mary McCormack
Mary Steenburgen
Mary-Louise Parker
Mason Lee
Mateo Arias
Mathieu Amalric
Matt Bomer
Matt Damon
Matt Lanter
Matt Long
Matthew Fox
Matthew Goode
Matthew Macfadyen
Matthew Marsden
Matthew McConaughey
Matthew Morrison
Matthew Perry
Matthew Zuk
Matthias Schoenaerts
Maude Apatow
Mauricio Lopez
Max Burkholder
Max Greenfield
Max Irons
Max Martini
Max Minghella
Max von Sydow
Maya Rudolph
McCaul Lombardi
Megan Charpentier
Megan Fox
Megan Park
Mel Gibson
Mel Raido
Melanie Laurent
Melissa Benoist
Melissa Leo
Melissa McCarthy
Meryl Streep
Mia Goth
Mia Stallard
Mia Wasikowska
Michael B. Jordan
Michael C. Hall
Michael Caine
Michael Cera
Michael Chiklis
Michael Constantine
Michael Dickson
Michael Douglas
Michael Ealy
Michael Fassbender
Michael Gambon
Michael Keaton
Michael Kelly
Michael Kenneth Williams
Michael Mantell
Michael McDonald
Michael McElhatton
Michael Nyqvist
Michael Parks
Michael Pena
Michael Pitt
Michael Rooker
Michael Shannon
Michael Sheen
Michael Stuhlbarg
Michael Trucco
Michael Vartan
Michael Yare
Michelle Monaghan
Michelle Pfeiffer
Michelle Rodriguez
Michelle Williams
Michelle Yeoh
Michiel Huisman
Mickey Rourke
Mike Vogel
Mila Kunis
Miles Heizer
Miles Teller
Milla Jovovich
Milo Ventimiglia
Min-sik Choi
Mindy Kaling
Mira Sorvino
Miranda Cosgrove
Mireille Enos
Miyavi
Mo'Nique
Moe Dunford
Mohamed Akhzam
Moises Acevedo
Moises Arias
Momo Dione
Moon Bloodgood
Morena Baccarin
Morgan Freeman
Morgan Lily
Morgan Saylor
Nadine Velazquez
Nancy Kwan
Naomi Watts
Naomie Harris
Nat Wolff
Natalie Martinez
Natalie Portman
Natascha McElhone
Natasha Henstridge
Nathalie Baye
Nathalie Boltt
Nathan Fillion
Nathan Phillips
Nazanin Boniadi
Ned Beatty
Neel Sethi
Neil Patrick Harris
Nellie
Ni Ni
Nia Vardalos
Nicholas Braun
Nicholas Galitzine
Nicholas Hope
Nicholas Hoult
Nick Frost
Nick Krause
Nick Nolte
Nick Offerman
Nick Robinson
Nick Swardson
Nicola Peltz
Nicolas Cage
Nicole Beharie
Nicole Kidman
Nicole Parker
Nikki Blonsky
Nikolaj Coster-Waldau
Nina Dobrev
Noah Ringer
Noah Taylor
Noah Wiseman
Noel Fisher
Noomi Rapace
Oakes Fegley
Oaklee Pendergast
Octavia Spencer
Odeya Rush
Olga Kurylenko
Oliver Cooper
Oliver Platt
Olivia Colman
Olivia Cooke
Olivia DeJonge
Olivia Luccardi
Olivia Munn
Olivia Thirlby
Olivia Wilde
Olivia Williams
Oona Chaplin
Oona Laurence
Ophelia Lovibond
Oprah Winfrey
Orlando Bloom
Orto Ignatiussen
Oscar Isaac
Owen Wilson
Pablo Schreiber
Paddy Considine
Patricia Arquette
Patricia Clarkson
Patrick Dempsey
Patrick Stewart
Patrick Wilson
Paul Anderson
Paul Bettany
Paul Birchard
Paul Dano
Paul Giamatti
Paul Newman
Paul Reiser
Paul Rudd
Paul Walker
Paula Beer
Paula Patton
Paula Prentiss
Penelope Cruz
Penelope Wilton
Penn Badgley
Peter Dinklage
Peter Facinelli
Peter McRobbie
Peter Riegert
Peter Sarsgaard
Peter Stormare
Peyton List
Philip Seymour Hoffman
Phylicia Rashad
Pierce Brosnan
Pierre Coffin
Pierre Niney
Portia Doubleday
Queen Latifah
Quinton Aaron
Quvenzhane Wallis
RJ Cyler
Rabah Nait Oufella
Rachael Blake
Rachael Harris
Rachel Bilson
Rachel Blanchard
Rachel House
Rachel Korine
Rachel McAdams
Rachel Weisz
Rachel Wood
Radha Mitchell
Raffey Cassidy
Raghuvir Joshi
Rainn Wilson
Ralph Fiennes
Ralph Ineson
Randall Park
Randy Couture
Rasmus Hardiker
Ray Romano
Ray Stevenson
Ray Winstone
Rebecca Ferguson
Rebecca Hall
Rebel Wilson
Reese Witherspoon
Regina Hall
Rene Russo
Renee Zellweger
Rhona Mitra
Rhys Ifans
Riccardo Scamarcio
Richard Armitage
Richard Dreyfuss
Richard Gere
Richard Jenkins
Richard Madden
Richenda Carey
Rihanna
Rila Fukushima
Riley Keough
Riley Thomas Stewart
Rima Te Wiata
Rinko Kikuchi
Rip Torn
Riz Ahmed
Rizwan Manji
Rob Corddry
Rob Riggle
Robbie Amell
Robert Capron
Robert Carlyle
Robert De Niro
Robert Downey Jr.
Robert Duvall
Robert Knepper
Robert Patrick
Robert Pattinson
Robert Redford
Robert Sheehan
Robin Williams
Robin Wright
Rodrigo Santoro
Romain Duris
Ron Livingston
Ron Perlman
Ronnie Gene Blevins
Rooney Mara
Rory Cochrane
Rory J. Saper
Rosamund Pike
Rosario Dawson
Rose Byrne
Rose Leslie
Rose McGowan
Rosemarie DeWitt
Rosie Huntington-Whiteley
Rosie Shaw
Ross Kimball
Ruben Blades
Ruby Barnhill
Rufus Sewell
Rupert Friend
Rupert Grint
Russell Brand
Russell Crowe
Ruth Negga
Ruth Wilson
Ryan Gosling
Ryan Guzman
Ryan Lee
Ryan Potter
Ryan Reynolds
Ryoko Seta
Sacha Baron Cohen
Salim Kechiouche
Salli Richardson-Whitfield
Sally Field
Sally Hawkins
Sally Phillips
Salma Hayek
Sam Claflin
Sam Elliott
Sam Neill
Sam Riley
Sam Rockwell
Sam Shepard
Sam Trammell
Sam Worthington
Samantha Isler
Samantha Morton
Samantha Sloyan
Samuel L. Jackson
Sandra Bullock
Sandra Kinder
Sanjeev Bhaskar
Saoirse Ronan
Sarah Clarke
Sarah Dumont
Sarah Gadon
Sarah Jessica Parker
Sarah Paulson
Sarah Polley
Sarah Roemer
Sarah Silverman
Sarah Snook
Sarita Choudhury
Sasha Lane
Saurabh Shukla
Scarlett Johansson
Scott Adsit
Scott Eastwood
Scott Glenn
Scott Lawrence
Scott Mescudi
Scott Speedman
Sean Bean
Sean Bott
Sean Bridgers
Sean Faris
Sean Patrick Thomas
Sean Penn
Sebastian Stan
Selena Gomez
Selma Blair
Seth MacFarlane
Seth Rogen
Shad Moss
Shailene Woodley
Shameik Moore
Shannon Woodward
Shariff Earp
Sharlto Copley
Shawn Roberts
Shea Adams
Sheila Kelley
Shia LaBeouf
Shiloh Fernandez
Sienna Guillory
Sienna Miller
Sigourney Weaver
Sigrid Bouaziz
Simon Helberg
Simon Pegg
Skyler Gisondo
Sofia Black-D'Elia
Sonoya Mizuno
Soo-an Kim
Sophie Nelisse
Sophie Okonedo
Sophie Perry
Stacy Martin
Stanley Tucci
Steele Stebbins
Stellan Skarsgard
Stephen Dorff
Stephen Henderson
Stephen Lang
Stephen Merchant
Stephen Moyer
Stephen Rea
Steve Buscemi
Steve Carell
Steve Coogan
Steve Lantz
Steve Martin
Steve Tom
Steve Wiebe
Steve Zahn
Steven Mackintosh
Steven Yeun
Storm Acheche Sahlstrom
Su Elliot
Sue Dahlman
Sullivan Stapleton
Sunny Pawar
Suraj Sharma
Susan Sarandon
Sylvester Stallone
Sylvia Hoeks
T.I.
T.J. Miller
T.R. Knight
Tabu
Tadanobu Asano
Taika Waititi
Taissa Farmiga
Tammy Blanchard
Tangie Ambrose
Tania Raymonde
Tao Okamoto
Taraji P. Henson
Taron Egerton
Taylor Kitsch
Taylor Lautner
Taylor Schilling
Taylor Swift
Ted Levine
Temuera Morrison
Terence Stamp
Teresa Palmer
Teri Hatcher
Terrence Howard
Terry Crews
Tessa Thompson
Teyonah Parris
Thandie Newton
Theo James
Theo Rossi
Thomas Brodie-Sangster
Thomas Haden Church
Thomas Jane
Thomas Lennon
Thomas M. Wright
Thomas Mann
Thomas Middleditch
Tian Jing
Tijuana Ricks
Til Schweiger
Tilda Swinton
Tim Allen
Tim Blake Nelson
Tim McGraw
Tim Roth
Timothy Olyphant
Timothy Spall
Tina Fey
Tobey Maguire
Tobias Menzies
Toby Jones
Toby Kebbell
Tom Costello
Tom Cruise
Tom Cullen
Tom Felton
Tom Hanks
Tom Hardy
Tom Hiddleston
Tom Holland
Tom Hughes
Tom Mison
Tom Prior
Tom Sizemore
Tom Wilkinson
Tommy Lee Jones
Toni Collette
Tony Amendola
Tony Danza
Tony Goldwyn
Tony Revolori
Tony Shalhoub
Topher Grace
Tracy Letts
Travis Fimmel
Travis Tope
Trenton Rogers
Trey Songz
Ty Simpkins
Tye Sheridan
Tyler Hoechlin
Tyler James Williams
Tyler Perry
Tyne Daly
Tyrese Gibson
Usher Raymond
Val Kilmer
Valerie Mahaffey
Vanessa Ferlito
Vanessa Hudgens
Vanessa Lachey
Vera Farmiga
Vernetta Lopez
Vicky Krieps
Victoria Justice
Viggo Mortensen
Vin Diesel
Vince Vaughn
Vincent Cassel
Vincent D'Onofrio
Vincent Ebrahim
Vincent Kartheiser
Ving Rhames
Vinnie Jones
Viola Davis
Walton Goggins
Ward Horton
Wei Tang
Wendi McLendon-Covey
Wendy Crewson
Wentworth Miller
Wenwen Han
Werner Herzog
Wes Bentley
Will Arnett
Will Dalton
Will Ferrell
Will Poulter
Will Smith
Will Yun Lee
Willem Dafoe
William Fichtner
William Hurt
Winona Ryder
Woody Allen
Woody Harrelson
Xavier Samuel
Yoo Gong
Yu-mi Jung
Zac Efron
Zac Mattoon O'Brien
Zach Galifianakis
Zach Grenier
Zachary Bennett
Zachary Gordon
Zachary Levi
Zachary Quinto
Zachery Ty Bryan
Zoe Bell
Zoe Kazan
Zoe Kravitz
Zoe Saldana
Zoey Deutch
Zooey Deschanel""".replace("\n", ",")

def strip_all(iterable: list[str]) -> tuple:
    return tuple(map(lambda x: x.strip(), iterable))

print(set(strip_all(MY_ANS_Q4.split(","))) == set(strip_all(OTHER_ANS_Q4.split(","))))
print(set(strip_all(MY_ANS_Q5.split(","))) == set(strip_all(OTHER_ANS_Q5.split(","))))
print(set(strip_all(MY_ANS_Q6.split(","))) == set(strip_all(OTHER_ANS_Q6.split(","))))
print(set(strip_all(MY_ANS_Q7.split(","))) == set(strip_all(OTHER_ANS_Q7.split(","))))
